config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  devise_for :users
  resources :posts do
    resources :votes
  end
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :votes
  belongs_to :user

  validates :title, presence: true
  validates :url, presence: true, format: { with: /\Ahttp/ }


  def votes_count
    votes.up.count - votes.down.count
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :votes
  has_many :posts

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  enum direction: [:up, :down]
  scope :recent, -> { where(created_at: 1.week.ago..Time.now) }

  after_create :send_email

  def send_email
    VoteMailer.notification(self, post).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new params[:post].permit(:title, :description, :url)
    @post.user = current_user
    
    if @post.save
      redirect_to '/posts'
    else
      render 'new'
    end

  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  before_action :authenticate_user!

  def create
    @post = Post.find params[:post_id]
    @vote = @post.votes.new direction: params[:direction]
    @vote.user = current_user

    if @vote.save
      render json: { vote_count: @post.votes_count }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Redditclone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class = 'container'>
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
	<%= yield %>
</div>
</body>
</html>

app/views/posts/index.html.erb
<% if @posts.any? %>
	<% @posts.each do |post| %>
		<div class = 'post'>
			<h3><%= link_to post.title, post.url %></h3>
			<h2 class='votes_count'><%= post.votes_count %></h2>
			<p><%= button_to 'Upvote', post_votes_path(post, direction: :up), class: 'vote_button btn btn-success' %></p>
			<p><%= button_to 'Downvote', post_votes_path(post, direction: :down), class: 'vote_button btn btn-danger' %></p>
			<p><%= post.description %></p>
		</div>
	<% end %>
<% else %>
	No posts yet
<% end %>

app/views/posts/new.html.erb
<%= bootstrap_form_for @post do |f| %>
	<%= f.text_field :title %>
	<%= f.text_area :description %>
	<%= f.text_field :url %>
	<%= f.submit 'Submit', class: "btn btn-default" %>
<% end %>